#!/bin/bash

source[0]="main.c"
source[1]="ran1.c"
source[2]="tqli.c"
source[3]="CLMC_memoria.c"
source[4]="CLMC_correlacoes.c"
source[5]="CLMC_PVI.c"
source[6]="CLMC_arquivos.c"
source[7]="CLMC_rk4.c"
source[8]="CLMC_rk8.c"
source[9]="CLMC_rk14.c"

usage(){
   cat << EOF
Use:
$0 [help] | [x]
   Argumento:         Uso:
   help               Exibir esta menssagem
   x                  Executar depois de compilar
   c                  Guardar os arquivos do programa em CLMC.zip
EOF
}

compile(){
   if clang ${source[@]} -o CLMC -lm; then
      return 0
   else
      return 1
   fi
}

if [ "$#" == 0 ]; then
   compile
   exit $?
else
   for arg in "$@"; do
      if [ "$arg" == "c" ]; then
         if [ -e CLMC.zip ]; then rm CLMC.zip; fi
         dir="tmp/CLMC"
         mkdir -p $dir
         for f in ${source[@]}; do
            cp $f $dir
         done
         cp CLMC.h $dir
         cp CLMC_configuracao.h $dir
         cp COMPILE $dir
         cp rk8.h $dir
         cp rk14.h $dir
         cd $dir/..
         zip -r CLMC.zip CLMC > /dev/null 2>&1
         mv CLMC.zip ../
         cd ../
         rm -r tmp
         exit 0
      elif [ "$arg" == "help" ] || [ "$arg" == "h" ]; then
         usage
         exit 0
      elif [ "$arg" == "x" ]; then
         compile
         if ! [ -d data ]; then env mkdir data; fi
         cd data
         time ../CLMC
         exit $?
      fi
      usage
      echo "$arg não reconhecido"
      exit 1
   done
fi
